-- Generated by Oracle SQL Developer Data Modeler 4.0.3.853
--   at:        2014-12-15 18:02:45 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE Booking
  (
    booking_ID                 INTEGER NOT NULL ,
    vehicle_ID                 INTEGER NOT NULL ,
    insurance_ID               INTEGER ,
    gadget_ID                  INTEGER ,
    booking_from_date          DATE NOT NULL ,
    booking_to_date            DATE NOT NULL ,
    booking_email_confirmation INTEGER NOT NULL ,
    fuel_fee                   NUMBER NOT NULL ,
    repair_fee                 NUMBER NOT NULL ,
    Cost FLOAT NOT NULL
  ) ;
ALTER TABLE Booking ADD CONSTRAINT Booking_PK PRIMARY KEY ( booking_ID ) ;

CREATE TABLE Brand
  (
    brand_ID FLOAT NOT NULL ,
    brand_name VARCHAR2 (45) NOT NULL ,
    model_name VARCHAR2 (45) NOT NULL ,
    Category   VARCHAR2 (45) NOT NULL
  ) ;
ALTER TABLE Brand ADD CONSTRAINT Brand_PK PRIMARY KEY ( brand_ID ) ;

CREATE TABLE Custumer
  (
    custumer_ID          INTEGER NOT NULL ,
    custumer_driving_ID  INTEGER NOT NULL ,
    custumer_first_name  VARCHAR2 (20) NOT NULL ,
    custumer_second_name VARCHAR2 (20) NOT NULL ,
    email_adress         VARCHAR2 (30) NOT NULL ,
    contact_number       INTEGER NOT NULL ,
    adress               VARCHAR2 (20) NOT NULL ,
    zip_code             INTEGER NOT NULL ,
    city                 VARCHAR2 (20) NOT NULL ,
    state                VARCHAR2 (20) ,
    country              VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE Custumer ADD CONSTRAINT Custumer_PK PRIMARY KEY ( custumer_ID ) ;

CREATE TABLE Gadget
  (
    gadget_ID INTEGER NOT NULL ,
    Gad_type  VARCHAR2 (45) NOT NULL
  ) ;
ALTER TABLE Gadget ADD CONSTRAINT Gadget_PK PRIMARY KEY ( gadget_ID ) ;

CREATE TABLE Insurance
  (
    insurance_ID INTEGER NOT NULL ,
    ins_type     VARCHAR2 (30) NOT NULL
  ) ;
ALTER TABLE Insurance ADD CONSTRAINT Insurance_PK PRIMARY KEY ( insurance_ID ) ;

CREATE TABLE Veh_Av
  (
    veh_av_ID      INTEGER NOT NULL ,
    vehicle_ID     INTEGER NOT NULL ,
    is_avail_until DATE ,
    is_avail_from  DATE
  ) ;
ALTER TABLE Veh_Av ADD CONSTRAINT Veh_Av_PK PRIMARY KEY ( veh_av_ID ) ;

CREATE TABLE Vehicles
  (
    vehicle_ID INTEGER NOT NULL ,
    brand_ID FLOAT NOT NULL ,
    vehicle_current_km INTEGER NOT NULL ,
    Car_engine_size FLOAT NOT NULL ,
    Price NUMBER NOT NULL
  ) ;
ALTER TABLE Vehicles ADD CONSTRAINT Vehicles_PK PRIMARY KEY ( vehicle_ID ) ;

CREATE TABLE cust_book
  (
    custumer_ID INTEGER NOT NULL ,
    booking_ID  INTEGER NOT NULL
  ) ;
ALTER TABLE cust_book ADD CONSTRAINT cust_book_PK PRIMARY KEY ( custumer_ID, booking_ID ) ;

ALTER TABLE Booking ADD CONSTRAINT Booking_Gadget_FK FOREIGN KEY ( gadget_ID ) REFERENCES Gadget ( gadget_ID ) ;

ALTER TABLE Booking ADD CONSTRAINT Booking_Insurance_FK FOREIGN KEY ( insurance_ID ) REFERENCES Insurance ( insurance_ID ) ;

ALTER TABLE Booking ADD CONSTRAINT Booking_Vehicles_FK FOREIGN KEY ( vehicle_ID ) REFERENCES Vehicles ( vehicle_ID ) ;

ALTER TABLE cust_book ADD CONSTRAINT FK_ASS_4 FOREIGN KEY ( custumer_ID ) REFERENCES Custumer ( custumer_ID ) ;

ALTER TABLE cust_book ADD CONSTRAINT FK_ASS_5 FOREIGN KEY ( booking_ID ) REFERENCES Booking ( booking_ID ) ;

ALTER TABLE Veh_Av ADD CONSTRAINT Veh_Av_Vehicles_FK FOREIGN KEY ( vehicle_ID ) REFERENCES Vehicles ( vehicle_ID ) ;

ALTER TABLE Vehicles ADD CONSTRAINT Vehicles_Brand_FK FOREIGN KEY ( brand_ID ) REFERENCES Brand ( brand_ID ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0